### ISSUE TITLE
Paste text from word document complete to first paragraph

### ISSUE THREAD

**Issue by torgashov** [kothing/Kothing-Editor#1]
When i paste copied  from MsWord 2013 document into editor, i get text only before first paragraph.
Problem in method until.js/cleanHtml
replacement regular expression: 
.replace(/<([a-zA-Z]+\:[a-zA-Z]+|script|style).*>(\n|.)*<\/([a-zA-Z]+\:[a-zA-Z]+|script|style)>/g, '')

**Comment by torgashov** [comment]
I am sorry, can you write issue solution? Will you fix bug, or ignore?

**Comment by kothing** [comment]
> I am sorry, can you write issue solution? Will you fix bug, or ignore?

fixed
